# Generated by Django 5.2.7 on 2025-11-03 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='default_shipping',
            field=models.BooleanField(default=False),
        ),
    ]
